Traceback (most recent call last):
  File "/Users/alex/Documents/Coding/rhythm_pattern_explorer/serve-app.py", line 97, in <module>
    main()
  File "/Users/alex/Documents/Coding/rhythm_pattern_explorer/serve-app.py", line 94, in main
    serve_app(args.port)
  File "/Users/alex/Documents/Coding/rhythm_pattern_explorer/serve-app.py", line 49, in serve_app
    with socketserver.TCPServer(("", port), CORSHTTPRequestHandler) as httpd:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/socketserver.py", line 456, in __init__
    self.server_bind()
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/socketserver.py", line 472, in server_bind
    self.socket.bind(self.server_address)
OSError: [Errno 48] Address already in use
